networks:
  - id: "stargaze"
    hrp: "stars"
    protocol: "cosmos"
    domain: 7865 # stargaze -> ascii / decimal -> sum
    endpoint:
      rpc: "http://localhost:21657"
      rest: "http://localhost:1316"
      grpc: "http://127.0.0.1:8090"
    gas:
      price: 1000
      denom: "ustars"
    nativeCurrency:
      name: "stars"
      symbol: "stars"
      decimals: 6
  - id: "lazy"
    hrp: ""
    protocol: "ethereum"
    domain: 11820
    endpoint:
      jsonrpc: "http://localhost:8545"
      rpc: ""
      rest: "http://localhost:1317"
      grpc: "http://127.0.0.1:9090"
    gas:
      price: 1000
      denom: "aart"
    network: "test"
    nativeCurrency:
      name: "art"
      symbol: "ART"
      decimals: 18
  - id: "forma"
    hrp: ""
    protocol: "ethereum"
    domain: 1337
    endpoint:
      jsonrpc: "http://localhost:8546"
      rpc: ""
      rest: ""
      grpc: ""
    gas:
      price: 1000
      denom: "utia"
    network: "test"
    nativeCurrency:
      name: "tia"
      symbol: "TIA"
      decimals: 18
